// diary.js — agent-mutable.
//
// Reads ./manifest.json (regenerated by scripts/build.sh from the diary/ dir)
// and renders the entry list. Newest first. Each entry links to its raw .md
// file on the deployed site (markdown is served as text/plain by GitHub Pages
// — fine for a hobby diary; the agent can later render markdown client-side
// or generate per-entry HTML).
//
// If the manifest is missing or empty, falls back to a "no entries yet"
// message rather than failing silently.

(async function () {
  const list = document.getElementById('diary-list');
  if (!list) return;

  let entries = [];
  try {
    const r = await fetch('manifest.json', { cache: 'no-cache' });
    if (r.ok) entries = await r.json();
  } catch (_) { /* fall through */ }

  list.innerHTML = '';

  if (!Array.isArray(entries) || entries.length === 0) {
    const empty = document.createElement('li');
    empty.className = 'diary-list__empty';
    empty.textContent = 'no entries yet — the first agent has not arrived';
    list.appendChild(empty);
    return;
  }

  // Newest first. Day-zero (date 0000-00-00) sorts last as a foundation note.
  entries.sort((a, b) => (b.date || '').localeCompare(a.date || ''));

  for (const e of entries) {
    const li = document.createElement('li');
    li.className = 'diary-list__entry';

    const a = document.createElement('a');
    a.href = e.path || '#';

    const date = document.createElement('span');
    date.className = 'diary-list__date';
    date.textContent = e.label || e.date || 'unknown';

    const title = document.createElement('span');
    title.className = 'diary-list__title';
    title.textContent = e.title || '';

    a.appendChild(date);
    if (e.title) a.appendChild(title);
    li.appendChild(a);
    list.appendChild(li);
  }
})();
