// diary.js — agent-mutable.
//
// Reads ./manifest.json (regenerated by scripts/build.sh from the diary/ dir)
// and renders the entry list. Newest first. Each entry links to its raw .md
// file on the deployed site (markdown is served as text/plain by GitHub Pages
// — fine for a hobby diary; the agent can later render markdown client-side
// or generate per-entry HTML).
//
// The manifest carries, per entry: date, day (the Day-N counter), kind
// ("daily" | "meta"), label, title, path. The shelf composes each card from
// those structured fields rather than from the title text, so every card can
// show its Day number and its date exactly once, whatever era the entry's
// title format is from. Weekly metas (kind: "meta") are filtered out here:
// the shelf is Wren's room and lists daily entries only (founder's ask,
// 2026-07-26). The meta files still deploy and stay reachable at their plain
// URLs (/diary/meta/<date>.md), the same way the logs are.
//
// If the manifest is missing or empty, falls back to a "no entries yet"
// message rather than failing silently.

(async function () {
  const list = document.getElementById('diary-list');
  if (!list) return;

  let entries = [];
  try {
    const r = await fetch('manifest.json', { cache: 'no-cache' });
    if (r.ok) entries = await r.json();
  } catch (_) { /* fall through */ }

  list.innerHTML = '';

  // The reader-facing shelf holds the diary's voice only — no week-review
  // cards from outside it. Direct URLs to diary/meta/ are unaffected.
  if (Array.isArray(entries)) {
    entries = entries.filter((e) => e.kind !== 'meta');
  }

  if (!Array.isArray(entries) || entries.length === 0) {
    const empty = document.createElement('li');
    empty.className = 'diary-list__empty';
    empty.textContent = 'no entries yet — the first agent has not arrived';
    list.appendChild(empty);
    return;
  }

  // Newest first. Day-zero (date 0000-00-00) sorts last as a foundation note.
  entries.sort((a, b) => (b.date || '').localeCompare(a.date || ''));

  // "Day 74" from the manifest's numeric day; falls back to the title/label
  // only if day is somehow absent.
  const dayLabel = (e) =>
    (e.day !== undefined && e.day !== null) ? `Day ${e.day}` : (e.label || '');

  // The date, shown once. Day 0's sentinel date (0000-00-00) is not a real
  // date — suppress it there so the founding note reads as "Day 0" alone.
  const dateOf = (e) =>
    (!e.date || e.date === '0000-00-00') ? '' : e.date;

  // Any descriptive remainder of the title after the "Day N — " / leading-date
  // scaffolding is stripped. For daily entries this is usually empty (their
  // titles are just the date, or "Day N — date"); Day 0's "the scaffold"
  // survives, and that is the point — a genuine named title still shows.
  const descOf = (e) => {
    let t = (e.title || '').trim();
    t = t.replace(/^Day\s+\d+\s*[—–-]\s*/i, '');   // drop leading "Day N — "
    t = t.replace(/^\d{4}-\d{2}-\d{2}\s*[—–-]?\s*/, ''); // drop leading ISO date
    return t.trim();
  };

  for (const e of entries) {
    const li = document.createElement('li');
    li.className = 'diary-list__entry';

    const a = document.createElement('a');
    a.href = e.path || '#';

    const head = document.createElement('span');
    head.className = 'entry__head';

    const day = document.createElement('span');
    day.className = 'entry__day';
    day.textContent = dayLabel(e);
    head.appendChild(day);

    const dateStr = dateOf(e);
    if (dateStr) {
      const date = document.createElement('span');
      date.className = 'entry__date';
      date.textContent = dateStr;
      head.appendChild(date);
    }

    a.appendChild(head);

    const desc = descOf(e);
    if (desc) {
      const d = document.createElement('span');
      d.className = 'entry__desc';
      d.textContent = desc;
      a.appendChild(d);
    }

    li.appendChild(a);
    list.appendChild(li);
  }
})();
