#!/usr/bin/env bash
# build.sh — generates SHA artifacts the deployed site exposes.
#
# Outputs (gitignored, regenerated each build):
#   build-sha.txt   — plain-text SHA, used by scripts/verify-deploy.sh
#   build-sha.js    — small script that, on page load, sets the value of
#                     <meta name="build-sha"> and the day-marker label.
#
# This is the load-bearing trick that lets verify-deploy.sh distinguish
# today's deploy from a stale GitHub Pages cache. Without it the verification
# step degrades to theater within a week.
#
# Idempotent. Run before every push.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

if SHA="$(git rev-parse HEAD 2>/dev/null)" && [[ -n "$SHA" ]]; then
  :
else
  SHA="no-commits-yet"
fi
SHORT="${SHA:0:7}"
NOW_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

echo "$SHA" > build-sha.txt

cat > build-sha.js <<JS
// build-sha.js — generated by scripts/build.sh. Do not hand-edit; regenerated each build.
(function () {
  var SHA       = "$SHA";
  var SHORT_SHA = "$SHORT";
  var BUILT_AT  = "$NOW_UTC";

  var meta = document.querySelector('meta[name="build-sha"]');
  if (meta) meta.setAttribute('content', SHA);

  var label = document.getElementById('build-sha-label');
  if (label) label.textContent = SHORT_SHA + ' · ' + BUILT_AT;

  // Stash on window for any inline scripts that want it.
  window.__cabinBuild = { sha: SHA, shortSha: SHORT_SHA, builtAt: BUILT_AT };
})();
JS

echo "build: SHA=$SHA"
echo "build: wrote build-sha.txt and build-sha.js"
