#!/usr/bin/env bash
# build.sh — generates SHA artifacts the deployed site exposes.
#
# Outputs (gitignored, regenerated each build):
#   build-sha.txt   — plain-text SHA, used by scripts/verify-deploy.sh
#   build-sha.js    — small script that, on page load, sets the value of
#                     <meta name="build-sha"> and the day-marker label.
#
# This is the load-bearing trick that lets verify-deploy.sh distinguish
# today's deploy from a stale GitHub Pages cache. Without it the verification
# step degrades to theater within a week.
#
# Idempotent. Run before every push.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

if SHA="$(git rev-parse HEAD 2>/dev/null)" && [[ -n "$SHA" ]]; then
  :
else
  SHA="no-commits-yet"
fi
SHORT="${SHA:0:7}"
NOW_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
TODAY_ISO="$(date -u +%Y-%m-%d)"

# Day-1 anchor — must match scripts/run-day.sh and the routine prompt.
# Edit here if Day 1 ever needs to shift.
DAY_ONE_DATE="2026-05-09"

# Compute day_n. Negative values mean "before Day 1" — render as "Day 0".
DAY_N="$(python3 - "$DAY_ONE_DATE" "$TODAY_ISO" <<'PY'
import sys, datetime
day_one = datetime.date.fromisoformat(sys.argv[1])
today   = datetime.date.fromisoformat(sys.argv[2])
n = (today - day_one).days + 1
print(max(0, n))
PY
)"
DAY_LABEL="Day ${DAY_N}"

echo "$SHA" > build-sha.txt

cat > build-sha.js <<JS
// build-sha.js — generated by scripts/build.sh. Do not hand-edit; regenerated each build.
(function () {
  var SHA       = "$SHA";
  var SHORT_SHA = "$SHORT";
  var BUILT_AT  = "$NOW_UTC";
  var DAY_N     = $DAY_N;
  var DAY_LABEL = "$DAY_LABEL";

  var meta = document.querySelector('meta[name="build-sha"]');
  if (meta) meta.setAttribute('content', SHA);

  var sha_label = document.getElementById('build-sha-label');
  if (sha_label) sha_label.textContent = SHORT_SHA + ' · ' + BUILT_AT;

  var day_label = document.getElementById('day-label');
  if (day_label) day_label.textContent = DAY_LABEL;

  // Stash on window for any inline scripts that want it.
  window.__cabinBuild = { sha: SHA, shortSha: SHORT_SHA, builtAt: BUILT_AT, dayN: DAY_N, dayLabel: DAY_LABEL };
})();
JS

echo "build: SHA=$SHA"
echo "build: wrote build-sha.txt and build-sha.js"

# Generate diary/manifest.json from diary/*.md AND diary/meta/*.md so the
# diary index page can render the full archive client-side.
# Schema: array of {date, day, kind, label, title, path}.
#   day:  the Day-N counter, from the filename date vs the Day-1 anchor
#         2026-05-09 (day-zero file -> 0)
#   kind: "daily" | "meta" (weekly Sunday meta-reflections live in meta/)
# title is the first H1 of each entry; date is taken from the filename.
python3 - <<'PY'
import datetime, json, re, pathlib

root = pathlib.Path("diary")
ANCHOR = datetime.date(2026, 5, 9)  # Day 1
out = []

def day_n(date_str):
    if date_str == "0000-00-00":
        return 0
    try:
        return (datetime.date.fromisoformat(date_str) - ANCHOR).days + 1
    except ValueError:
        return None

for md in sorted(root.glob("*.md")) + sorted((root / "meta").glob("*.md")):
    name = md.name
    if name == "README.md":
        continue
    # Filename forms: YYYY-MM-DD.md  or  0000-00-00-day-zero.md
    m = re.match(r'^(\d{4}-\d{2}-\d{2})(?:-.*)?\.md$', name)
    if not m:
        continue
    date = m.group(1)
    kind = "meta" if md.parent.name == "meta" else "daily"

    # Pull the first H1 line from the file as the title.
    title = ""
    try:
        with md.open("r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("# "):
                    title = line[2:].strip()
                    break
    except Exception:
        pass

    label = "Day 0" if date == "0000-00-00" else date

    out.append({
        "date":  date,
        "day":   day_n(date),
        "kind":  kind,
        "label": label,
        "title": title,
        "path":  name if kind == "daily" else f"meta/{name}",
    })

manifest_path = root / "manifest.json"
manifest_path.write_text(json.dumps(out, indent=2) + "\n")
print(f"build: wrote {manifest_path} ({len(out)} entries)")
PY
